//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoYP0101
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int Id { get; set; }
        public int AdressId { get; set; }
        public int UserId { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
        public int ExecutorId { get; set; }
    
        public virtual Executor Executor { get; set; }
        public virtual ListHousingStock ListHousingStock { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
